# Generated by Django 5.1.1 on 2024-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SorteioCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('CPF', models.TextField(max_length=255)),
                ('RG', models.TextField(max_length=255)),
                ('Orgao', models.TextField(max_length=255)),
                ('Emissao', models.DateField()),
                ('Cidade_Nascimento', models.TextField(max_length=255)),
                ('Data_Nascimento', models.DateField()),
                ('Endereco', models.TextField(max_length=255)),
                ('Setor_Bairro', models.TextField(max_length=255)),
                ('Quadra', models.TextField(max_length=255)),
                ('Lote', models.TextField(max_length=255)),
                ('Apartamento', models.TextField(max_length=255)),
                ('Complemento', models.TextField(max_length=255)),
                ('Cidade', models.TextField(max_length=255)),
                ('CEP', models.IntegerField()),
                ('Estado', models.TextField(max_length=255)),
                ('Telefone', models.TextField(max_length=255)),
                ('Email', models.TextField(max_length=255)),
                ('Sexo', models.TextField(max_length=255)),
                ('documento', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
